SET search_path TO projet;


-- Schéma

DROP SCHEMA IF EXISTS projet CASCADE;
CREATE SCHEMA projet AUTHORIZATION projet;
GRANT ALL PRIVILEGES ON SCHEMA projet TO projet;


-- Tables

CREATE TABLE compte (
	IdCompte		INT			 	NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
	Pseudo			VARCHAR(25)		NOT NULL,
	MotDePasse		VARCHAR(25) 	NOT NULL,
	Email			VARCHAR(100)	NOT NULL,
	PRIMARY KEY (IdCompte)
);
CREATE UNIQUE INDEX idx_compte_pseudo ON compte (Pseudo ASC);

CREATE TABLE role (
	IdCompte		INT				NOT NULL,
	Role			VARCHAR(20)		NOT NULL,
	CHECK( Role IN ('ADMINISTRATEUR','UTILISATEUR') ),	
	FOREIGN KEY (IdCompte) REFERENCES compte (IdCompte),
	PRIMARY KEY (IdCompte, Role)
);

CREATE TABLE utilisateur (
	idutilisateur	INT				NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nom				VARCHAR(50)		NOT NULL,
	prenom			VARCHAR(50)		NOT NULL,
	email			VARCHAR(50)		NOT NULL,
	motdepasse		VARCHAR(50)		NOT NULL,
	role			VARCHAR(20)		NOT NULL,
	CHECK( role IN('PARENT','GESTIONNAIRE')),
	paiement		INT 			NOT NULL,
	PRIMARY KEY (idutilisateur)
);

CREATE TABLE enfant (
	idenfant				INT				NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	idutilisateur		INT			 	NOT NULL,
	nom				VARCHAR(50)		NOT NULL,
	prenom			VARCHAR(50)		NOT NULL,
	datedenaissance	DATE			NOT NULL,
	etabfrequente	VARCHAR(50)		NOT NULL,
	niveauetude		VARCHAR(20)		NOT NULL,
	CHECK(niveauetude IN('SIXIEME', 'CINQUIEME', 'QUATRIEME', 'TROISIEME', 'SECONDE', 'PREMIERE', 'TERMINALE')),
	creneauchoisi	TIME			NOT NULL,
	modedepaiement	VARCHAR(20)		NOT NULL,
	CHECK( modedepaiement IN('CHEQUE', 'ESPECES', 'VIREMENT')),
	FOREIGN KEY (idutilisateur) REFERENCES utilisateur (idutilisateur),
	PRIMARY KEY(idenfant)
);

CREATE TABLE cours (
	idcours			INT				NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nom			VARCHAR(20)		NOT NULL,
	CHECK(nom IN('MATHEMATIQUES','ANGLAIS','PHYSIQUE','CHIMIE','INFORMATIQUE')),
	creneaudispo	 VARCHAR(30) 	NOT NULL,
	CHECK(creneaudispo IN('MERCREDI: 16H00-18H00','JEUDI: 18H00-20H00','VENDREDI: 18H00-20H00','SAMEDI: 10H00-12H00','14H00-16H00','DIMANCHE: 10H00-12H00','14H00-16H00')),
	PRIMARY KEY (Idcours)
);
